
server:
  port: 80

## spring datasource
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    # Initialize the datasource with available DDL and DML scripts
    initialization-mode: always

## hibernate properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: 'create-drop'
    defer-datasource-initialization: true # data.sql 초기화를 flyway 및 Liquibase 동작과 일치시킴
## Hibernate Logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
