

## spring datasource
spring:
  datasource:
    url: jdbc:mysql://192.168.0.100:3306/calendartodo?useSSL=false&useLegacyDateTimeCode=false&serverTimezone=Asia/Seoul
    username: calendartodo
    password: calendartodo2022!
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: org.h2.Driver
    # Initialize the datasource with available DDL and DML scripts
    initialization-mode: NEVER

## hibernate properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: 'update'
    defer-datasource-initialization: true # data.sql 초기화를 flyway 및 Liquibase 동작과 일치시킴
## Hibernate Logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
