# This is a basic workflow to help you get started with Actions

name: GitHub Actions Maven Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v3
        with:
          node-version: '14'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Install and Build Front-end
        working-directory: ./front-end
        run:
          npm install
          npm run build --if-present

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Maven Project
        run: mvn -B package --file pom.xml

      - name: Copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: './target/ROOT.jar'
          target: '~/build'

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Excuting remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          timeout: 40s
          script: |
            java -jar target/ROOT.jar -Dspring.profiles.action=dev

