# This is a basic workflow to help you get started with Actions

name: GitHub Actions Maven Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v3
        with:
          node-version: '14'

      # Runs a single command using the runners shell
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Install and Build Front-end
        working-directory: ./front-end
        run:
          npm install
          npm run build --if-present

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Runs a set of commands using the runners shell
      - name: Build Maven Project
        run: mvn -B package --file pom.xml

      - name: List the current directory
        run: ls -a

      - name: What is in the target folder?
        run:
          cd target
          ls -a
